DROP TABLE IF EXISTS User_Movie;
DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Movie;


CREATE TABLE User (
    UserID SERIAL PRIMARY KEY,
    Username VARCHAR(255) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    Email VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE Movie (
    MovieID SERIAL PRIMARY KEY,
    Title VARCHAR(255) NOT NULL,
    Genre VARCHAR(100) NOT NULL,
    ReleaseYear INT NOT NULL
);

CREATE TABLE User_Movie (
    UserID INT NOT NULL,
    MovieID INT NOT NULL,
    DateAdded DATE NOT NULL,
    FOREIGN KEY (UserID) REFERENCES User(UserID),
    FOREIGN KEY (MovieID) REFERENCES Movie(MovieID),
    PRIMARY KEY (UserID, MovieID)
);
